version: 2
jobs:
  build:
    environment:
      GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:1.10
    working_directory: /home/circleci/go/src/github.com/gemcook/peger-go
    steps:
      - run:
          name: show information
          command: |
            echo pwd \"$(pwd)\"
            echo go version \"$(go version)\"
            echo go env \"$(go env)\"
      - run: 
          name: add GOPATH/bin to PATH
          command: |
            echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: 
          name: install go tools
          command: |
            go get github.com/golang/lint/golint
      - run: 
          name: lint 
          command: |
            golint ./...
            go vet ./...
      - run: 
          name: unit test 
          command: |
            go test -v -race -coverprofile=./coverage.text ./...
      - run: 
          name: code coverage 
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
